const palette = {
  sage: "#7e8e72",
  sageDark: "#5e6b56",
  sageLight: "#cdd6c1",
  sageMist: "#e6ebe0",
  cream: "#f5ecd5",
  creamSoft: "#faf5e6",
  forest: "#2d3a2a",
  forestSoft: "#3f4f3a",
  ochre: "#b8754a",
  ochreLight: "#d99467",
  bark: "#5b4a39",
  paper: "#fffaf0",
  ink: "#1f2620",
  mist: "#8a8f85",
};

const colors = {
  light: {
    text: palette.ink,
    tint: palette.sage,
    background: palette.creamSoft,
    foreground: palette.ink,
    card: "#ffffff",
    cardForeground: palette.ink,
    primary: palette.sage,
    primaryForeground: "#ffffff",
    secondary: palette.sageMist,
    secondaryForeground: palette.forest,
    muted: palette.cream,
    mutedForeground: palette.bark,
    accent: palette.ochre,
    accentForeground: "#ffffff",
    accentSoft: "#f4dccb",
    destructive: "#a13a2a",
    destructiveForeground: "#ffffff",
    border: "#e4dcc4",
    input: "#efe7d0",
    sage: palette.sage,
    sageDark: palette.sageDark,
    sageLight: palette.sageLight,
    sageMist: palette.sageMist,
    cream: palette.cream,
    forest: palette.forest,
    ochre: palette.ochre,
    bark: palette.bark,
  },
  highContrast: {
    text: "#000000",
    tint: "#1a3d12",
    background: "#fffdf6",
    foreground: "#000000",
    card: "#ffffff",
    cardForeground: "#000000",
    primary: "#1a3d12",
    primaryForeground: "#ffffff",
    secondary: "#dde7d4",
    secondaryForeground: "#000000",
    muted: "#f1ead0",
    mutedForeground: "#1a1a1a",
    accent: "#7a3a14",
    accentForeground: "#ffffff",
    accentSoft: "#f4dccb",
    destructive: "#7a1a0a",
    destructiveForeground: "#ffffff",
    border: "#1a1a1a",
    input: "#ffffff",
    sage: "#1a3d12",
    sageDark: "#0e2a08",
    sageLight: "#a8b89d",
    sageMist: "#dde7d4",
    cream: "#fff8e0",
    forest: "#000000",
    ochre: "#7a3a14",
    bark: "#000000",
  },
  radius: 14,
};

export default colors;
