kind = "mobile"
previewPath = "/mobile/"
title = "Accessilife Mobile"
version = "1.0.0"
id = "artifacts/accessilife-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/mobile/" ]
localPort = 21357

[services.development]
run = "pnpm --filter @workspace/accessilife-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/accessilife-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/accessilife-mobile", "run", "serve" ]

[services.env]
PORT = "21357"
BASE_PATH = "/mobile/"
